function redirect()
{
	var x=document.getElementById("gamesl").value;
	if(x=="Assassin's Creed IV: Black Flag")
		window.location.assign("http://localhost:8080/web_technology/pages/game1.html")
	if(x=="Assassin's Creed Syndicate")
		window.location.assign("http://localhost:8080/web_technology/pages/game2.html")
	if(x=="Ashes Cricket 2013")
		window.location.assign("http://localhost:8080/web_technology/pages/game3.html")
	if(x=="Battlefield 1")
		window.location.assign("http://localhost:8080/web_technology/pages/game4.html")
	if(x=="Battlefield 4")
		window.location.assign("http://localhost:8080/web_technology/pages/game5.html")
	if(x=="Burnout Paradise")
		window.location.assign("http://localhost:8080/web_technology/pages/game6.html")
	if(x=="Call of Duty: Infinite Warfare")
		window.location.assign("http://localhost:8080/web_technology/pages/game7.html")
	if(x=="Call of Duty: Black Ops")
		window.location.assign("http://localhost:8080/web_technology/pages/game8.html")
	if(x=="Counter-Strike: Global Offensive")
		window.location.assign("http://localhost:8080/web_technology/pages/game9.html")
	if(x=="Cricket 07")
		window.location.assign("http://localhost:8080/web_technology/pages/game10.html")
	if(x=="Crysis 2")
		window.location.assign("http://localhost:8080/web_technology/pages/game11.html")
	if(x=="Crysis 3")
		window.location.assign("http://localhost:8080/web_technology/pages/game12.html")
	if(x=="Don Bradman Cricket 17")
		window.location.assign("http://localhost:8080/web_technology/pages/game13.html")
	if(x=="Don Bradman Cricket 14")
		window.location.assign("http://localhost:8080/web_technology/pages/game14.html")
	if(x=="Dirt 3")
		window.location.assign("http://localhost:8080/web_technology/pages/game15.html")
	if(x=="Dirt Rally")
		window.location.assign("http://localhost:8080/web_technology/pages/game16.html")
	if(x=="Far Cry 3")
		window.location.assign("http://localhost:8080/web_technology/pages/game17.html")
	if(x=="Far Cry Primal")
		window.location.assign("http://localhost:8080/web_technology/pages/game18.html")
	if(x=="FIFA 17")
		window.location.assign("http://localhost:8080/web_technology/pages/game19.html")
	if(x=="FIFA 16")
		window.location.assign("http://localhost:8080/web_technology/pages/game20.html")
	if(x=="FIFA 15")
		window.location.assign("http://localhost:8080/web_technology/pages/game21.html")
	if(x=="FIFA 14")
		window.location.assign("http://localhost:8080/web_technology/pages/game22.html")
	if(x=="Grid 2")
		window.location.assign("http://localhost:8080/web_technology/pages/game23.html")
	if(x=="Grand Theft Auto IV")
		window.location.assign("http://localhost:8080/web_technology/pages/game24.html")
	if(x=="Grand Theft Auto V")
		window.location.assign("http://localhost:8080/web_technology/pages/game25.html")
	if(x=="Need for Speed Rivals")
		window.location.assign("http://localhost:8080/web_technology/pages/game26.html")
	if(x=="Need for Speed: Most Wanted 2012")
		window.location.assign("http://localhost:8080/web_technology/pages/game27.html")
	if(x=="Need for Speed (2015)")
		window.location.assign("http://localhost:8080/web_technology/pages/game28.html")
	if(x=="Prince of Persia: Warrior Within")
		window.location.assign("http://localhost:8080/web_technology/pages/game29.html")
	if(x=="Prince of Persia: The Forgotten Sands")
		window.location.assign("http://localhost:8080/web_technology/pages/game30.html")
	if(x=="Pro Evolution Soccer 2017")
		window.location.assign("http://localhost:8080/web_technology/pages/game31.html")
	if(x=="Prototype")
		window.location.assign("http://localhost:8080/web_technology/pages/game32.html")
	if(x=="Prototype 2")
		window.location.assign("http://localhost:8080/web_technology/pages/game33.html")
	if(x=="Titanfall")
		window.location.assign("http://localhost:8080/web_technology/pages/game34.html")
	if(x=="Virtua Tennis 4")
		window.location.assign("http://localhost:8080/web_technology/pages/game35.html")
}